Mélissa 005 fusion sans modif
Yunis78/eportager_finale pull request #25
Opened 2021-05-05 19:15 UTC by MelissaPas

2021-05-05 19:47 UTC, Naltpom requested changes

2021-05-05 19:47 UTC, Naltpom commented on src/Repository/ProducerRepository.php
> +        return $this->findBy([], ['id'=>'DESC'], $limit, $offset);
fait ca directement dans le controller ->findBy([], 2, 2)
Inutile de le faire ici car c'est ajouter des lignes pour rien :)

2021-05-05 19:47 UTC, Naltpom commented on src/Controller/DefaultController.php
> +            'producers' => $producerRepository->findLastNb(2,0),
utilise findBy directement ici

2021-05-05 19:47 UTC, Naltpom commented on src/Controller/ProducerController.php
> +            // 'controller_name' => 'FrontProducteursController',
il faut supprimer les commentaire qui ne sont pas utilise

2021-05-05 19:47 UTC, Naltpom commented on src/Controller/ProducerController.php
> +            // 'controller_name' => 'FrontProducteursController',
commentaire inutile

2021-05-05 19:47 UTC, Naltpom commented on src/DataFixtures/ORM/MediaFixtures.php
> +            // 'path' => 'pomme.jpg',
commentaire inutile

2021-05-05 19:47 UTC, Naltpom commented on src/DataFixtures/ORM/MediaFixtures.php
> +            // 'product' => 'pomme-15-4',
commentaire inutile

2021-05-05 19:47 UTC, Naltpom commented on src/DataFixtures/ORM/ProductFixtures.php
> +            // 'categorie' => 'fruits',
commentaire inutile

2021-05-05 19:47 UTC, Naltpom commented on src/DataFixtures/ORM/ProductFixtures.php
> +            // 'categorie' => 'legumes',
commentaire inutile

2021-05-05 19:47 UTC, Naltpom commented on templates/base.html.twig
>                      <button class="btn btnvert ml-3 dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ri-user-3-fill"></i></button>
code utile pour plus tard ?

2021-05-05 19:47 UTC, Naltpom commented on templates/components/pages/default/accessCRUD.html.twig
> +        {#}
code utile pour plus tard sinon a delete

2021-05-05 19:47 UTC, Naltpom commented on templates/components/pages/default/index.html.twig
> +                                <div class="card-body">
code utile pour plus tard ? a delete si c'est pas nesessaire

2021-05-05 19:47 UTC, Naltpom commented on templates/components/pages/producer/producer_list.html.twig
> +        {#}
pareil code en commentaire

2021-05-05 21:57 UTC, MelissaPas commented on src/Repository/ProducerRepository.php
> +        return $this->findBy([], ['id'=>'DESC'], $limit, $offset);
pour la lisibilité

2021-05-06 00:24 UTC, Naltpom approved these changes

2021-05-06 00:25 UTC, merged